webtalk_init -webtalk_dir c:/nn-project/nn_base/nn_base.tmp/nn_axi_v1_0_project/nn_axi_v1_0_project.sim/sim_1/behav/xsim.dir/user_app_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr 16 22:25:11 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2016.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1756540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "28ab7830-f6cc-4c34-ac5a-e0b0f643bf5d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e507fd5a09704a2698dc0b532aa1c852" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-4500U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12524_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3790154170 -regid "" -xml c:/nn-project/nn_base/nn_base.tmp/nn_axi_v1_0_project/nn_axi_v1_0_project.sim/sim_1/behav/xsim.dir/user_app_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html c:/nn-project/nn_base/nn_base.tmp/nn_axi_v1_0_project/nn_axi_v1_0_project.sim/sim_1/behav/xsim.dir/user_app_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm c:/nn-project/nn_base/nn_base.tmp/nn_axi_v1_0_project/nn_axi_v1_0_project.sim/sim_1/behav/xsim.dir/user_app_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
