# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.cache/wt [current_project]
set_property parent.project_path /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs
  /home/nlandy/Documents/Reconfig/Project/ip_repo/nnip_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library work {
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/imports/accelerator_1.0/src/config_pkg.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/imports/accelerator_1.0/src/user_pkg.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/imports/distributable/fixed_float_types_c.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/imports/distributable/fixed_pkg_c.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/imports/new/heap_arr_pkg.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/absfixed.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/MAC.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/sigmablock.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/neuron.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/neural_layer.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/hidden_layer.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/neural_network.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/neural_network_top.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/nn_wrapper.vhd
  /home/nlandy/Documents/Reconfig/Project/neural_network/neural_network.srcs/sources_1/new/parameter.vhd
}
synth_design -top neural_network_top -part xc7z020clg484-1 -flatten_hierarchy full
write_checkpoint -noxdef neural_network_top.dcp
catch { report_utilization -file neural_network_top_utilization_synth.rpt -pb neural_network_top_utilization_synth.pb }
