# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/edit_nn_axi_v3_v1_0.cache/wt [current_project]
set_property parent.project_path /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/edit_nn_axi_v3_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v2_1.0
  /home/nlandy/EEL4720-Neural-Network-Project_copy/ip_repo/nn_axi_1.0
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library work {
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/fixed_float_types_c.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/fixed_pkg_c.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/heap_arr_pkg.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/absfixed.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/sigmablock.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/MAC.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/neuron.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/neural_layer.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/hidden_layer.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/neural_network.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/neural_network_top.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/config_pkg.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/ram.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/nn_wrapper.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/mem_map.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/user_app.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/nn_axi_v1_0_S00_AXI.vhd
  /home/nlandy/EEL4720-Neural-Network-Project_copy/nn_base/ip_repo/nn_axi_v3_1.0/src/nn_axi_v1_0.vhd
}
synth_design -top nn_axi_v1_0 -part xc7z020clg484-1
write_checkpoint -noxdef nn_axi_v1_0.dcp
catch { report_utilization -file nn_axi_v1_0_utilization_synth.rpt -pb nn_axi_v1_0_utilization_synth.pb }
